/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PP_Prototype;

public class App {
   
    public static void main(String[] args) {
        
        T4i prototipoCanon1 = new T4i();
        D5D prototipoCanon2 = new D5D();
        
        CanonPrototype T4inova = prototipoCanon1.clonar();
        T4inova.setValorCompra(2500);
        
        CanonPrototype T4iusada = prototipoCanon1.clonar();
        T4iusada.setValorCompra(1000);
        
        System.out.println(T4inova.exibirInfo());
        System.out.println(T4iusada.exibirInfo());
        
        CanonPrototype D5nova = prototipoCanon2.clonar();
        D5nova.setValorCompra(15000);
        
        CanonPrototype D5usada = prototipoCanon2.clonar();
        D5usada.setValorCompra(5000);
        
        System.out.println(D5nova.exibirInfo());
        System.out.println(D5usada.exibirInfo());
        
        CanonPrototype T4ComAcessorios = prototipoCanon1.clonar();
        T4ComAcessorios.setValorCompra(6000);
        System.out.println(T4ComAcessorios.exibirInfo());
    }
}
